import type { GenesisCheckpoint, GenesisProgress } from "./types";
export const GENESIS_CHECKPOINTS: GenesisCheckpoint[] = [
  { index: 0, title: "The Signal Ridge", narrative: "A fractured beacon is broadcasting from the ridge. Choose how to approach its unstable signal.", choices: [{ id: "scan", title: "Scan the beacon", description: "Map the safe route before moving.", momentum: 2 }, { id: "rush", title: "Rush the ridge", description: "Move fast and claim the high ground.", momentum: 1 }, { id: "salvage", title: "Salvage nearby parts", description: "Trade speed for a sturdier path.", momentum: 0 }] },
  { index: 1, title: "The Glass Crossing", narrative: "The route divides over a field of mirrored glass. Every move changes the map ahead.", choices: [{ id: "anchor", title: "Set an anchor line", description: "A deliberate route keeps the team steady.", momentum: 2 }, { id: "drift", title: "Follow the light", description: "A fast route, but the terrain may shift.", momentum: 1 }, { id: "detour", title: "Take the quiet detour", description: "Lose time to preserve your resources.", momentum: 0 }] },
  { index: 2, title: "The Relic Gate", narrative: "The gate opens for a Pathfinder willing to commit to a final approach.", choices: [{ id: "align", title: "Align the signal", description: "Use the route data to open the gate precisely.", momentum: 2 }, { id: "override", title: "Override the lock", description: "Force a quick opening at moderate risk.", momentum: 1 }, { id: "stabilize", title: "Stabilize the core", description: "Protect the route before taking the relic.", momentum: 0 }] },
];
export function initialGenesisProgress(): GenesisProgress { return { checkpointIndex: 0, momentum: 0, history: [] }; }
export function checkpointFor(progress: GenesisProgress): GenesisCheckpoint | null { return GENESIS_CHECKPOINTS[progress.checkpointIndex] ?? null; }
export function resolveChoice(seed: string, progress: GenesisProgress, choiceId: string): GenesisProgress { const checkpoint = checkpointFor(progress); if (!checkpoint) throw new Error("No checkpoint is available"); const choice = checkpoint.choices.find(item => item.id === choiceId); if (!choice) throw new Error("Invalid checkpoint choice"); const deterministicRisk = (hashSeed(`${seed}:${checkpoint.index}:${choiceId}`) % 3) - 1; const momentum = progress.momentum + choice.momentum + deterministicRisk; return { checkpointIndex: progress.checkpointIndex + 1, momentum, history: [...progress.history, { checkpoint: checkpoint.index, choiceId, momentum }] }; }
function hashSeed(value: string): number { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
export function calculateLevel(experience: number): number { return Math.floor(Math.sqrt(Math.max(0, experience) / 100)) + 1; }
export function experienceToNextLevel(experience: number): number { const nextLevel = calculateLevel(experience) + 1; return Math.max(0, (nextLevel - 1) ** 2 * 100 - experience); }
